# Generated by Django 5.1.1 on 2024-09-16 00:09

import django.core.validators
import payment_scheduler.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(validators=[payment_scheduler.validates.date_validate])),
                ('permite_recorrencia', models.BooleanField()),
                ('quantidade_recorrencia', models.IntegerField()),
                ('intervalo_recorrencia', models.IntegerField()),
                ('status_recorrencia', models.CharField(max_length=100)),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('valor_pagamento', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
