# Generated by Django 5.1.1 on 2024-09-16 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentscheduler',
            unique_together={('data_pagamento', 'agencia', 'conta', 'valor_pagamento', 'permite_recorrencia', 'quantidade_recorrencia', 'intervalo_recorrencia', 'status_recorrencia')},
        ),
    ]
