# Generated by Django 5.1.1 on 2024-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentscheduler',
            constraint=models.UniqueConstraint(fields=('data_pagamento', 'agencia', 'conta', 'valor_pagamento', 'permite_recorrencia', 'quantidade_recorrencia', 'intervalo_recorrencia', 'status_recorrencia'), name='unique_payment_scheduler', violation_error_message='Já existe um agendamento com esta combinação de campos.'),
        ),
    ]
