# Generated by Django 5.1.1 on 2024-09-15 00:03

import payment_scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_scheduler', '0002_alter_paymentscheduler_valor_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheduler',
            name='data_pagamento',
            field=models.DateField(validators=[payment_scheduler.models.date_validate]),
        ),
    ]
