# Generated by Django 5.1.1 on 2024-09-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_scheduler', '0003_alter_paymentscheduler_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheduler',
            name='valor_pagamento',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
