# Generated by Django 5.1.1 on 2024-09-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_scheduler', '0004_alter_paymentscheduler_valor_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentscheduler',
            name='valor_pagamento',
            field=models.IntegerField(),
        ),
    ]
